controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: position_controllers/JointGroupPositionController

    arm_effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_effort_controller:
      type: position_controllers/JointGroupPositionController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

arm_controller:
  ros__parameters:
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll

    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    # Add this to prevent movement on startup
    start_position_control: false
    hold_position_on_startup: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint_trajectory_controller:
        joint1:
          trajectory: 0.05
          goal: 0.03
gripper_controller:
  ros__parameters:
    joints:
      - Gripper
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

arm_effort_controller:
  ros__parameters:
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    start_position_control: false
    hold_position_on_startup: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    gains:
      Shoulder_Rotation: {p: 75.0, i: 0.0, d: 1.0}
      Shoulder_Pitch: {p: 75.0, i: 0.0, d: 1.0}
      Elbow: {p: 75.0, i: 0.0, d: 1.0}
      Wrist_Pitch: {p: 75.0, i: 0.0, d: 1.0}
      Wrist_Roll: {p: 75.0, i: 0.0, d: 1.0}

gripper_effort_controller:
  ros__parameters:
    joints:
      - Gripper
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      Gripper: {p: 75.0, i: 0.0, d: 1.0}

effort_controller:
  ros__parameters:
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll
      - Gripper
